
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author simon
 */
public class Buscatore extends javax.swing.JFrame {
	//"AND-BooleanQuery", "PhraseQuery", "PalabraQuery"
	

    private Boolean[][] selected=new Boolean[][]{{false, false, false},{false,false,false},{false,false,false}};
    private Searcher_interfaz proIndex;
    private String resultado_busqueda;
    /**
     * Creates new form Buscatore
     */
    public Buscatore() {
        initComponents();
        Searcher_interfaz proIndex=null;   
        resultado_busqueda=new String();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        query_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        result_area = new javax.swing.JTextArea();
        query = new javax.swing.JTextField();
        query_types = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        facets_label = new javax.swing.JLabel();
        director_button = new javax.swing.JCheckBox();
        director0 = new javax.swing.JCheckBox();
        director1 = new javax.swing.JCheckBox();
        director2 = new javax.swing.JCheckBox();
        genre_button = new javax.swing.JCheckBox();
        genre0 = new javax.swing.JCheckBox();
        genre1 = new javax.swing.JCheckBox();
        genre2 = new javax.swing.JCheckBox();
        origin_button = new javax.swing.JCheckBox();
        origin0 = new javax.swing.JCheckBox();
        origin1 = new javax.swing.JCheckBox();
        origin2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione el tipo de consulta");

        query_button.setText("Buscar");
        query_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                query_buttonActionPerformed(evt);
            }
        });

        result_area.setColumns(20);
        result_area.setRows(5);
        jScrollPane1.setViewportView(result_area);

        query.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryActionPerformed(evt);
            }
        });

        query_types.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AND-BooleanQuery", "PhraseQuery", "PalabraQuery" }));

        facets_label.setText("FACETAS");

        director_button.setText("Director");
        director_button.setEnabled(false);
        director_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                director_buttonActionPerformed(evt);
            }
        });

        director0.setText("null");
        director0.setEnabled(false);
        director0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                director0ActionPerformed(evt);
            }
        });

        director1.setText("null");
        director1.setEnabled(false);
        director1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                director1ActionPerformed(evt);
            }
        });

        director2.setText("null");
        director2.setEnabled(false);
        director2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                director2ActionPerformed(evt);
            }
        });

        genre_button.setText("Genre");
        genre_button.setEnabled(false);
        genre_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genre_buttonActionPerformed(evt);
            }
        });

        genre0.setText("null");
        genre0.setEnabled(false);
        genre0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genre0ActionPerformed(evt);
            }
        });

        genre1.setText("null");
        genre1.setEnabled(false);
        genre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genre1ActionPerformed(evt);
            }
        });

        genre2.setText("null");
        genre2.setEnabled(false);
        genre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genre2ActionPerformed(evt);
            }
        });

        origin_button.setText("Origin/Ethnicity");
        origin_button.setEnabled(false);
        origin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origin_buttonActionPerformed(evt);
            }
        });

        origin0.setText("null");
        origin0.setEnabled(false);
        origin0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origin0ActionPerformed(evt);
            }
        });

        origin1.setText("null");
        origin1.setEnabled(false);
        origin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origin1ActionPerformed(evt);
            }
        });

        origin2.setText("null");
        origin2.setEnabled(false);
        origin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origin2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genre_button, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facets_label)
                            .addComponent(director_button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(origin2)
                                    .addComponent(origin0)
                                    .addComponent(origin1)
                                    .addComponent(director0)
                                    .addComponent(director1)
                                    .addComponent(director2)
                                    .addComponent(genre1)
                                    .addComponent(genre2)
                                    .addComponent(genre0)))))
                    .addComponent(origin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {director0, director1, director2, director_button, facets_label, genre0, genre1, genre2, genre_button, origin0, origin1, origin2, origin_button});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(facets_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(director_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(director0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(director1)
                .addGap(2, 2, 2)
                .addComponent(director2)
                .addGap(12, 12, 12)
                .addComponent(genre_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genre0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(origin_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(origin0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(origin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(origin2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        //jLabel2.setText("IMAGEN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(query_types, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(query, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(query_button))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(query_types, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(query, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(query_button))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>


    private void query_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_query_buttonActionPerformed
        // TODO add your handling code here:
        if(query.getText().isEmpty())
			JOptionPane.showMessageDialog(null, "Introduzca una consulta");
        else{
            String consulta=query.getText();
            String value = query_types.getSelectedItem().toString();
            
            proIndex= new Searcher_interfaz();
            resultado_busqueda = proIndex.indexSearchInterfaz(consulta, value);

            result_area.setText(null);
            result_area.append(resultado_busqueda);
            
            String[] matrix=proIndex.getPaMiJeje();
            
            director_button.setEnabled(true);
            director0.setText(matrix[0]);
            director0.setEnabled(true);
            director1.setText(matrix[1]);
            director1.setEnabled(true);
            director2.setText(matrix[2]);
            director2.setEnabled(true);
            
            genre_button.setEnabled(true);
            genre0.setText(matrix[3]);
            genre0.setEnabled(true);
            genre1.setText(matrix[4]);
            genre1.setEnabled(true);
            genre2.setText(matrix[5]);
            genre2.setEnabled(true);
            
            origin_button.setEnabled(true);
            origin0.setText(matrix[6]);
            origin0.setEnabled(true);
            origin1.setText(matrix[7]);
            origin1.setEnabled(true);
            origin2.setText(matrix[8]);
            origin2.setEnabled(true);
            
            /*for(String nose : matrix){
            	result_area.append("\n"+nose);
            }*/
            
            result_area.setCaretPosition(0);
                    
        }
    }
    
    
    private void selectAll(int ind, boolean nose){
        for(int i=0; i<3; i++){
            selected[ind][i]=nose;
        }
    }
    
    private void showFacetsInterfaz(){
        // TODO
        result_area.setText(null);
        /*for(int i=0; i<3; i++){
            for(int j=0; j<3; j++){
                result_area.append(" ------ " + Boolean.toString(selected[i][j]) + " ------ ");
            }
            result_area.append("\n");
        }*/
        
        
        String escogidas=new String();
        for(int i=0; i<3; i++){
        	for(int j=0; j<3; j++){
        		if(selected[i][j]){
        			int aniadir=i*3+j;
        			escogidas+=aniadir + ",";
        		}
        	}
        }
        
        if(!escogidas.equals("")){
        	//result_area.append(escogidas+"\n");
        
        	String result2= proIndex.filterSearchByFacets(escogidas);
        	
        	result_area.append(result2);
        }else{
        	//result_area.append("Ninguna\n");
        	result_area.append(resultado_busqueda);
        }
        
        result_area.setCaretPosition(0);
    }
    
    private void queryActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void director_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        director0.setSelected(director_button.isSelected());
        director1.setSelected(director_button.isSelected());
        director2.setSelected(director_button.isSelected());
        selectAll(0,director_button.isSelected());
        showFacetsInterfaz();
    }                                               

    private void genre_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        genre0.setSelected(genre_button.isSelected());
        genre1.setSelected(genre_button.isSelected());
        genre2.setSelected(genre_button.isSelected());
        selectAll(1,genre_button.isSelected());
        showFacetsInterfaz();
    }                                            

    private void origin_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        origin0.setSelected(origin_button.isSelected());
        origin1.setSelected(origin_button.isSelected());
        origin2.setSelected(origin_button.isSelected());
        selectAll(2,origin_button.isSelected());
        showFacetsInterfaz();
    }                                             

    private void director0ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        selected[0][0]=director0.isSelected();
        showFacetsInterfaz();
    }                                         

    private void director1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        selected[0][1]=director1.isSelected();
        showFacetsInterfaz();
    }                                         

    private void director2ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        selected[0][2]=director2.isSelected();
        showFacetsInterfaz();
    }                                         

    private void origin2ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        selected[2][2]=origin2.isSelected();
        showFacetsInterfaz();
    }                                       

    private void origin0ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        selected[2][0]=origin0.isSelected();
        showFacetsInterfaz();
    }                                       

    private void origin1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        selected[2][1]=origin1.isSelected();
        showFacetsInterfaz();
    }                                       

    private void genre0ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        selected[1][0]=genre0.isSelected();
        showFacetsInterfaz();
    }                                      

    private void genre1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        selected[1][1]=genre1.isSelected();
        showFacetsInterfaz();
    }                                      

    private void genre2ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        selected[1][2]=genre2.isSelected();
        showFacetsInterfaz();
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscatore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox director0;
    private javax.swing.JCheckBox director1;
    private javax.swing.JCheckBox director2;
    private javax.swing.JCheckBox director_button;
    private javax.swing.JLabel facets_label;
    private javax.swing.JCheckBox genre0;
    private javax.swing.JCheckBox genre1;
    private javax.swing.JCheckBox genre2;
    private javax.swing.JCheckBox genre_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox origin0;
    private javax.swing.JCheckBox origin1;
    private javax.swing.JCheckBox origin2;
    private javax.swing.JCheckBox origin_button;
    private javax.swing.JTextField query;
    private javax.swing.JButton query_button;
    private javax.swing.JComboBox<String> query_types;
    private javax.swing.JTextArea result_area;
    // End of variables declaration                   
}

