
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author simon
 */
public class Buscatore extends javax.swing.JFrame {

    private Boolean[][] selected=new Boolean[][]{{false, false, false},{false,false,false},{false,false,false}};
    /**
     * Creates new form Buscatore
     */
    public Buscatore() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        query_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        result_area = new javax.swing.JTextArea();
        query = new javax.swing.JTextField();
        query_types = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        origin0 = new javax.swing.JCheckBox();
        origin_button = new javax.swing.JCheckBox();
        origin1 = new javax.swing.JCheckBox();
        director1 = new javax.swing.JCheckBox();
        origin2 = new javax.swing.JCheckBox();
        genre0 = new javax.swing.JCheckBox();
        director0 = new javax.swing.JCheckBox();
        genre_button = new javax.swing.JCheckBox();
        director_button = new javax.swing.JCheckBox();
        genre2 = new javax.swing.JCheckBox();
        facets_label = new javax.swing.JLabel();
        director2 = new javax.swing.JCheckBox();
        genre1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione el tipo de consulta");

        query_button.setText("Buscar");
        query_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                query_buttonActionPerformed(evt);
            }
        });

        result_area.setColumns(20);
        result_area.setRows(5);
        jScrollPane1.setViewportView(result_area);

        query.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryActionPerformed(evt);
            }
        });

        query_types.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "a", "b", "c" }));

        origin0.setText("jCheckBox1");
        origin0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origin0ActionPerformed(evt);
            }
        });

        origin_button.setText("Origin/Ethnicity (0)");
        origin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origin_buttonActionPerformed(evt);
            }
        });

        origin1.setText("jCheckBox1");
        origin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origin1ActionPerformed(evt);
            }
        });

        director1.setText("jCheckBox1");
        director1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                director1ActionPerformed(evt);
            }
        });

        origin2.setText("jCheckBox1");
        origin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origin2ActionPerformed(evt);
            }
        });

        genre0.setText("jCheckBox1");

        director0.setText("jCheckBox1");
        director0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                director0ActionPerformed(evt);
            }
        });

        genre_button.setText("Genre (0)");
        genre_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genre_buttonActionPerformed(evt);
            }
        });

        director_button.setText("Director (0)");
        director_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                director_buttonActionPerformed(evt);
            }
        });

        genre2.setText("jCheckBox1");

        facets_label.setText("FACETAS");

        director2.setText("jCheckBox1");
        director2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                director2ActionPerformed(evt);
            }
        });

        genre1.setText("jCheckBox1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genre_button, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facets_label)
                            .addComponent(director_button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(origin2)
                                    .addComponent(origin0)
                                    .addComponent(origin1)
                                    .addComponent(director0)
                                    .addComponent(director1)
                                    .addComponent(director2)
                                    .addComponent(genre0)
                                    .addComponent(genre1)
                                    .addComponent(genre2)))))
                    .addComponent(origin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {director0, director1, director2, director_button, facets_label, genre0, genre1, genre2, genre_button, origin0, origin1, origin2, origin_button});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(facets_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(director_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(director0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(director1)
                .addGap(2, 2, 2)
                .addComponent(director2)
                .addGap(12, 12, 12)
                .addComponent(genre_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genre0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(origin_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(origin0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(origin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(origin2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(query_types, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(query, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(query_button))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(query_types, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(query, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(query_button))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void query_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_query_buttonActionPerformed
        // TODO add your handling code here:
        if(query.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Data Missing");
        else{
            String consulta=query.getText();
            //String varName = (String)query_types.getSelectedItem();
            String value = query_types.getSelectedItem().toString();
            result_area.setText(null);
            //result_area.append(consulta + "\n");
            //result_area.append(value);
            for(int i=0; i<3; i++){
                for(int j=0; j<3; j++){
                    result_area.append(" ------ " + Boolean.toString(selected[i][j]) + " ------ ");
                }
                result_area.append("\n");
            }
            
            
        }
    }//GEN-LAST:event_query_buttonActionPerformed

    private void selectAll(int ind, boolean nose){
        for(int i=0; i<3; i++){
            selected[ind][i]=nose;
        }
    }
    
    private void showFacetsInterfaz(){
        // TODO
        
    }
    
    private void queryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_queryActionPerformed

    private void director_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_director_buttonActionPerformed
        // TODO add your handling code here:
        //selected[0]=director_button.isSelected();
        director0.setSelected(director_button.isSelected());
        director1.setSelected(director_button.isSelected());
        director2.setSelected(director_button.isSelected());
        selectAll(0,director_button.isSelected());
    }//GEN-LAST:event_director_buttonActionPerformed

    private void genre_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genre_buttonActionPerformed
        // TODO add your handling code here:
        //selected[1]=genre_button.isSelected();
        genre0.setSelected(genre_button.isSelected());
        genre1.setSelected(genre_button.isSelected());
        genre2.setSelected(genre_button.isSelected());
        selectAll(0,genre_button.isSelected());
    }//GEN-LAST:event_genre_buttonActionPerformed

    private void origin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origin_buttonActionPerformed
        // TODO add your handling code here:
        //selected[2]=origin.isSelected();
        origin0.setSelected(origin_button.isSelected());
        origin1.setSelected(origin_button.isSelected());
        origin2.setSelected(origin_button.isSelected());
        selectAll(0,origin_button.isSelected());
    }//GEN-LAST:event_origin_buttonActionPerformed

    private void director0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_director0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_director0ActionPerformed

    private void director1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_director1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_director1ActionPerformed

    private void director2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_director2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_director2ActionPerformed

    private void origin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_origin2ActionPerformed

    private void origin0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origin0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_origin0ActionPerformed

    private void origin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_origin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscatore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox director0;
    private javax.swing.JCheckBox director1;
    private javax.swing.JCheckBox director2;
    private javax.swing.JCheckBox director_button;
    private javax.swing.JLabel facets_label;
    private javax.swing.JCheckBox genre0;
    private javax.swing.JCheckBox genre1;
    private javax.swing.JCheckBox genre2;
    private javax.swing.JCheckBox genre_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox origin0;
    private javax.swing.JCheckBox origin1;
    private javax.swing.JCheckBox origin2;
    private javax.swing.JCheckBox origin_button;
    private javax.swing.JTextField query;
    private javax.swing.JButton query_button;
    private javax.swing.JComboBox<String> query_types;
    private javax.swing.JTextArea result_area;
    // End of variables declaration//GEN-END:variables
}
